----------------------------------------------------------------------------------
-- Company       : University of Belgrade, School of Electrical Engineering (ETF)
-- Engineer      : Marko Gavrilović
-- Email         : markog0403@gmail.com
--
-- Create Date   : August 2026
-- Design Name   : tb_gf_sqr_vec
-- Module Name   : tb_gf_sqr_vec - sim
-- Tool Version  : GHDL (--std=08 -fsynopsys)
--
-- Description   : File-based test for gf_sqr (combinational squarer)
--                 Reads "<a> <exp>" vectors (G_M-wide bit strings, MSB left) from G_VEC_FILE,
--                 generated by the Python golden model. gf_sqr is combinational — no clock,
--                 just drive i_a, wait, compare o_sq.
--                 ghdl -r --std=08 tb_gf_sqr_vec -gG_M=4   -gG_VEC_FILE=gf_sqr_vec_gf4.txt
--                 ghdl -r --std=08 tb_gf_sqr_vec -gG_M=571 -gG_VEC_FILE=gf_sqr_vec_b571.txt
--
-- Revision      :
--   0.01 - August 2026 - File Created
----------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use std.textio.all;

entity tb_gf_sqr_vec is
    generic (
        G_M        : integer := 4;
        G_VEC_FILE : string  := "gf_sqr_vec_gf4.txt"
    );
end entity;

architecture sim of tb_gf_sqr_vec is

    function f_poly(m : integer) return std_logic_vector is
        variable v : std_logic_vector(m downto 0) := (others => '0');
    begin
        v(m) := '1';
        if m = 4 then
            v(1) := '1'; v(0) := '1';
        elsif m = 571 then
            v(10) := '1'; v(5) := '1'; v(2) := '1'; v(0) := '1';
        else
            report "f_poly: unknown field m=" & integer'image(m) severity failure;
        end if;
        return v;
    end function;

    signal a   : std_logic_vector(G_M-1 downto 0) := (others => '0');
    signal sq  : std_logic_vector(G_M-1 downto 0);

begin

    dut : entity work.gf_sqr
        generic map (G_M => G_M, G_F => f_poly(G_M))
        port map (i_a => a, o_sq => sq);

    p_main : process
        file     f_vec : text;
        variable l     : line;
        variable c     : character;
        variable ok    : boolean;
        variable va    : std_logic_vector(G_M-1 downto 0);
        variable vexp  : std_logic_vector(G_M-1 downto 0);
        variable n     : integer := 0;
        variable nfail : integer := 0;

        procedure read_bits(variable ln : inout line;
                            v  : out std_logic_vector) is
            variable ch : character;
            variable okc : boolean;
        begin
            for i in v'range loop
                read(ln, ch, okc);
                assert okc report "short line in vector file" severity failure;
                if ch = '1' then v(i) := '1'; else v(i) := '0'; end if;
            end loop;
        end procedure;
    begin
        file_open(f_vec, G_VEC_FILE, read_mode);
        while not endfile(f_vec) loop
            readline(f_vec, l);
            next when l'length = 0;
            read_bits(l, va);
            read(l, c, ok);              -- space
            read_bits(l, vexp);

            a <= va;
            wait for 1 ns;               -- let combinational logic settle

            n := n + 1;
            if sq /= vexp then
                nfail := nfail + 1;
                if nfail <= 8 then
                    report "FAIL vector " & integer'image(n-1) severity error;
                end if;
            end if;
        end loop;
        file_close(f_vec);

        if nfail = 0 then
            report "==== gf_sqr ALL " & integer'image(n) & " PASS (m="
                 & integer'image(G_M) & ") ====";
        else
            report "==== gf_sqr " & integer'image(nfail) & "/" & integer'image(n)
                 & " FAIL (m=" & integer'image(G_M) & ") ====" severity failure;
        end if;
        wait;
    end process;

end architecture;
