----------------------------------------------------------------------------------
-- Company       : University of Belgrade, School of Electrical Engineering (ETF)
-- Engineer      : Marko Gavrilović
-- Email         : markog0403@gmail.com
--
-- Create Date   : August 2026
-- Design Name   : tb_gf_inv_vec
-- Module Name   : tb_gf_inv_vec - sim
-- Tool Version  : GHDL (--std=08 -fsynopsys)
--
-- Description   : File-based test for gf_inv (shares gf_mul via mul-client port)
--                 Reads "<a> <exp>" vectors (G_M-wide bit strings, MSB left) from G_VEC_FILE,
--                 generated by gf2m.gf_inv (golden model). Instantiates gf_inv AND gf_mul and
--                 connects the gf_inv mul-client ports to one gf_mul instance (as the ALU will).
--                 ghdl -r --std=08 tb_gf_inv_vec -gG_M=4   -gG_VEC_FILE=inv_vec_gf4.txt
--                 ghdl -r --std=08 tb_gf_inv_vec -gG_M=571 -gG_VEC_FILE=inv_vec_b571.txt
--
-- Revision      :
--   0.01 - August 2026 - File Created
----------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_gf_inv_vec is
    generic (
        G_M        : integer := 4;
        G_D        : integer := 1;
        G_VEC_FILE : string  := "inv_vec_gf4.txt"
    );
end entity;

architecture sim of tb_gf_inv_vec is

    function f_poly(m : integer) return std_logic_vector is
        variable v : std_logic_vector(m downto 0) := (others => '0');
    begin
        v(m) := '1';
        if m = 4 then
            v(1) := '1'; v(0) := '1';                              -- x^4 + x + 1
        elsif m = 7 then
            v(1) := '1'; v(0) := '1';                              -- x^7 + x + 1
        elsif m = 571 then
            v(10) := '1'; v(5) := '1'; v(2) := '1'; v(0) := '1';   -- B-571 pentanomial
        else
            report "f_poly: unknown field m=" & integer'image(m) severity failure;
        end if;
        return v;
    end function;

    signal clk    : std_logic := '0';
    signal rstn   : std_logic := '0';
    signal done_s : boolean   := false;

    signal start  : std_logic := '0';
    signal a      : std_logic_vector(G_M-1 downto 0) := (others => '0');
    signal res    : std_logic_vector(G_M-1 downto 0);
    signal busy   : std_logic;
    signal done   : std_logic;

    -- mul-client bus between gf_inv and the shared gf_mul
    signal mi_start : std_logic;
    signal mi_a     : std_logic_vector(G_M-1 downto 0);
    signal mi_b     : std_logic_vector(G_M-1 downto 0);
    signal mi_done  : std_logic;
    signal mi_res   : std_logic_vector(G_M-1 downto 0);
    signal mi_busy  : std_logic;

begin

    clk <= not clk after 5 ns when not done_s else '0';

    dut : entity work.gf_inv
        generic map (G_M => G_M, G_F => f_poly(G_M))
        port map (
            i_clk => clk, i_resetn => rstn, i_start => start,
            i_a => a, o_res => res, o_busy => busy, o_done => done,
            o_mul_start => mi_start, o_mul_a => mi_a, o_mul_b => mi_b,
            i_mul_busy => mi_busy, i_mul_done => mi_done, i_mul_res => mi_res
        );

    -- SHARED gf_mul (provided by the TB here; by the ALU in the system)
    u_mul : entity work.gf_mul
        generic map (G_M => G_M, G_D => G_D, G_F => f_poly(G_M))
        port map (
            i_clk => clk, i_resetn => rstn, i_start => mi_start,
            i_a => mi_a, i_b => mi_b,
            o_res => mi_res, o_busy => mi_busy, o_done => mi_done
        );

    p_main : process
        file     f_vec : text;
        variable l     : line;
        variable c     : character;
        variable ok    : boolean;
        variable va    : std_logic_vector(G_M-1 downto 0);
        variable vexp  : std_logic_vector(G_M-1 downto 0);
        variable g     : integer;
        variable n     : integer := 0;
        variable nfail : integer := 0;

        procedure read_bits(variable ln : inout line;
                            v  : out std_logic_vector) is
            variable ch : character;
            variable okc : boolean;
        begin
            for i in v'range loop          -- (G_M-1 downto 0): first char -> bit G_M-1
                read(ln, ch, okc);
                assert okc report "short line in vector file" severity failure;
                if ch = '1' then v(i) := '1'; else v(i) := '0'; end if;
            end loop;
        end procedure;
    begin
        rstn <= '0';
        for i in 0 to 4 loop wait until rising_edge(clk); end loop;
        rstn <= '1';
        wait until rising_edge(clk);

        file_open(f_vec, G_VEC_FILE, read_mode);
        while not endfile(f_vec) loop
            readline(f_vec, l);
            next when l'length = 0;
            read_bits(l, va);
            read(l, c, ok);                -- space
            read_bits(l, vexp);

            a     <= va;
            start <= '1';
            wait until rising_edge(clk);
            start <= '0';

            g := 0;
            loop
                wait until rising_edge(clk);
                exit when done = '1';
                g := g + 1;
                assert g < 70*G_M + 500 report "TIMEOUT on vector "
                    & integer'image(n) severity failure;
            end loop;

            n := n + 1;
            if res /= vexp then
                nfail := nfail + 1;
                if nfail <= 8 then
                    report "FAIL vector " & integer'image(n-1) severity error;
                end if;
            end if;

            wait until rising_edge(clk);
        end loop;
        file_close(f_vec);

        if nfail = 0 then
            report "==== ALL " & integer'image(n) & " PASS (m="
                 & integer'image(G_M) & ") ====";
        else
            report "==== " & integer'image(nfail) & "/" & integer'image(n)
                 & " FAIL (m=" & integer'image(G_M) & ") ====" severity failure;
        end if;

        done_s <= true;
        wait;
    end process;

end architecture;
