#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Company  : University of Belgrade, School of Electrical Engineering (ETF)
# Engineer : Marko Gavrilović
# Email    : markog0403@gmail.com
#
# Does the model give the same answer as the FPGA?
#
# Golden vectors are generated BY THIS MODEL (emit_vector.py) and handed to the
# RTL length-sweep testbench, which drives the whole 5-core encryption chain at
# AES-256 and compares every ciphertext byte and the tag. A single mismatch
# means the model and the hardware disagree.
#
# Every AAD and PT residue mod 16 is swept, so the partial-block paths are
# covered, not just the aligned case.
#
#   ./check_vs_fpga.sh
# ---------------------------------------------------------------------------
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IP="$(cd "$HERE/../../ip_cores" && pwd)"
L3="$IP/L3_WRAPPER_IP_CORES"
CHAIN="$HERE/../l3_full_chain"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

G="ghdl -a --std=08 -fsynopsys --workdir=$WORK"
R="ghdl -r --std=08 -fsynopsys --workdir=$WORK"

echo "== analyze the RTL chain =="
$G "$IP/AES_ALGORITHM/src/aes_pkg.vhd" 2>/dev/null || exit 1
for f in key_expansion aes_round_column aes_round aes_enc_rolled aes_enc_pipelined \
         AES_multicore_wrapper AES_pipelined_wrapper AES_algorithm; do
  $G "$IP/AES_ALGORITHM/src/$f.vhd" || exit 1
done
for f in GF2_karatsuba_16 GF_karatsuba_32 GF_Karatsuba_64 GF2_Karatsuba_128 \
         GF2_Reduction_128 GF_multiplier GHASH GHASH_wrapper AXIS_skid_buffer \
         axis_broadcaster AXIS_DEMUX AXIS_GHASH_MUX AXIS_MUX Tag_Finalizer gcm_enc_glue; do
  $G "$IP/GCM_GLUE_ENC/src/$f.vhd" || exit 1
done
for f in AXIS_DEMUX_dec AXIS_MUX_DEC Tag_Verifier gcm_dec_glue; do
  $G "$IP/GCM_GLUE_DEC/src/$f.vhd" || exit 1
done
$G "$L3/SPLIT_demux/src/util_split.vhd"                      || exit 1
$G "$L3/SPLIT_demux/src/SPLIT_demux.vhd"                     || exit 1
$G "$L3/MERGE_mux/src/util_merge.vhd"                        || exit 1
$G "$L3/MERGE_mux/src/MERGE_mux.vhd"                         || exit 1
$G "$L3/ICV_realign/src/ICV_realign.vhd"                     || exit 1
$G "$L3/AXIS_full_skid_buffer/src/AXIS_full_skid_buffer.vhd" || exit 1
$G "$CHAIN/src/top_gcm_enc.vhd"                              || exit 1
$G "$CHAIN/tb/tb_gcm_kat_len.vhd"                            || exit 1
ghdl -e --std=08 -fsynopsys --workdir="$WORK" tb_gcm_kat_len || exit 1

echo
echo "== model (AES-256) vs the 5-core RTL chain =="
pass=0; fail=0
for A in 1 15 16 17 20 32 33; do
  for P in 1 15 16 17 31 60 63 64 65 100 127 129; do
    (cd "$HERE" && python3 emit_vector.py AES 16 "$A" "$P" "$WORK/vec.txt") || {
      fail=$((fail+1)); continue; }
    out=$($R tb_gcm_kat_len -gAES_BITS=256 -gAAD_BYTES=$A -gPT_BYTES=$P \
            -gVEC_FILE="$WORK/vec.txt" --assert-level=none 2>&1)
    if echo "$out" | grep -q "RESULT: PASS"; then
      pass=$((pass+1))
    else
      fail=$((fail+1))
      printf "FAIL  AAD=%-4s (mod16=%2s)  PT=%-4s (mod16=%2s)\n" \
             "$A" $((A%16)) "$P" $((P%16))
    fi
  done
done

echo
echo "-------------------------------------------"
echo "TOTAL: $((pass+fail))   PASS: $pass   FAIL: $fail"
[ $fail -ne 0 ] && { echo "THE MODEL AND THE FPGA DISAGREE"; exit 1; }
echo "ALL PASS — the model is bit-exact with the hardware"
